package model

import "time"

// SiteVisitor stores a one-way identifier for an anonymous browser visitor.
// The identifier is generated by the frontend and hashed before persistence.
type SiteVisitor struct {
	ID          string    `json:"id" gorm:"primaryKey;size:64"`
	FirstSeenAt time.Time `json:"first_seen_at" gorm:"not null"`
}

func (SiteVisitor) TableName() string { return "site_visitor" }
